H+Ae9xWSJTmzwoGE 02-01-2024

diff --git a/archdots/archdots b/archdots/archdots
--- a/archdots/archdots
+++ b/archdots/archdots
@@ -83,6 +83,7 @@ archdots_setup_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   \n" "$(green "all")            "
   printf "  %s   \n" "$(green "git_credentials")"
+  printf "  %s   \n" "$(green "defaults")       "
   printf "  %s   \n" "$(green "git_delta")      "
   printf "  %s   \n" "$(green "nvim")           "
   printf "  %s   \n" "$(green "evrouter")       "
@@ -171,6 +172,35 @@ archdots_setup_git_credentials_usage() {
   printf "%s\n" "Usage:"
   printf "  archdots setup git_credentials\n"
   printf "  archdots setup git_credentials --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_setup_defaults_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots setup defaults\n"
+    echo
+
+  else
+    printf "archdots setup defaults\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots setup defaults\n"
+  printf "  archdots setup defaults --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1329,6 +1359,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'setup defaults\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'setup evrouter\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -1414,7 +1448,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'setup\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups defaults docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'edit\'*)'
@@ -1513,6 +1547,19 @@ archdots_setup_git_credentials_command() {
 
   [ -n "$useremail" ]&&git config --global user.email "$useremail"||echo "Empty input. Did not change previous"
   [ -n "$username" ]&&git config --global user.name "$username"||echo "Empty input. Did not change previous"
+
+}
+
+# :command.function
+archdots_setup_defaults_command() {
+  # src/commands/setup/defaults.sh
+  #!/usr/bin/env bash
+
+  if [ "$1" = "check" ]; then
+  	exit
+  fi
+
+  gsettings set org.cinnamon.desktop.default-applications.terminal exec $(bsplaunch --query terminal)
 
 }
 
@@ -2302,6 +2349,13 @@ archdots_setup_parse_requirements() {
       shift $#
       ;;
 
+    defaults)
+      action="defaults"
+      shift
+      archdots_setup_defaults_parse_requirements "$@"
+      shift $#
+      ;;
+
     git_delta)
       action="git_delta"
       shift
@@ -2508,6 +2562,50 @@ archdots_setup_git_credentials_parse_requirements() {
 
   # :command.command_filter
   action="setup git_credentials"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+archdots_setup_defaults_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_setup_defaults_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="setup defaults"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -4127,6 +4225,7 @@ run() {
     "setup") archdots_setup_command ;;
     "setup all") archdots_setup_all_command ;;
     "setup git_credentials") archdots_setup_git_credentials_command ;;
+    "setup defaults") archdots_setup_defaults_command ;;
     "setup git_delta") archdots_setup_git_delta_command ;;
     "setup nvim") archdots_setup_nvim_command ;;
     "setup evrouter") archdots_setup_evrouter_command ;;
