dPXQ58lkkFhGdLoG 20-10-2023

diff --git a/archdots/archdots b/archdots/archdots
--- a/archdots/archdots
+++ b/archdots/archdots
@@ -34,15 +34,18 @@ archdots_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Run a setup script\n" "$(green "setup") "
-  printf "  %s   edit packages file\n" "$(green "edit")  "
-  printf "  %s   show diff since last dotfiles sync\n" "$(green "diff")  "
-  printf "  %s   Sync apps and dotfiles\n" "$(green "sync")  "
-  printf "  %s   go to chezmoi repo or pacdef groups folder location\n" "$(green "cd")    "
-  printf "  %s   review unmanaged packages\n" "$(green "review")"
-  printf "  %s   an alias for archdots git status\n" "$(green "status")"
-  printf "  %s   run git commands from chezmoi repo\n" "$(green "git")   "
-  printf "  %s   list packages (default) or tracked dotfiles\n" "$(green "list")  "
+  printf "  %s   Run a setup script\n" "$(green "setup")      "
+  printf "  %s   run \`eval \"\$(archdots completions)\"\` to add completions to your shell\n" "$(green "completions")"
+  printf "  %s   Add an existing file, directory, or symlink to the source state\n" "$(green "add")        "
+  printf "  %s   Remove a target from the source state\n" "$(green "forget")     "
+  printf "  %s   edit packages file\n" "$(green "edit")       "
+  printf "  %s   show diff since last dotfiles sync\n" "$(green "diff")       "
+  printf "  %s   Sync apps and dotfiles\n" "$(green "sync")       "
+  printf "  %s   go to chezmoi repo or pacdef groups folder location\n" "$(green "cd")         "
+  printf "  %s   review unmanaged packages\n" "$(green "review")     "
+  printf "  %s   an alias for archdots git status\n" "$(green "status")     "
+  printf "  %s   run git commands from chezmoi repo\n" "$(green "git")        "
+  printf "  %s   list packages (default) or tracked dotfiles\n" "$(green "list")       "
   echo
 
   # :command.long_usage
@@ -614,6 +617,109 @@ archdots_setup_cups_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots completions - run \`eval \"\$(archdots completions)\"\` to add completions to your shell\n"
+    echo
+
+  else
+    printf "archdots completions - run \`eval \"\$(archdots completions)\"\` to add completions to your shell\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots completions\n"
+  printf "  archdots completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_add_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots add - Add an existing file, directory, or symlink to the source state\n"
+    echo
+
+  else
+    printf "archdots add - Add an existing file, directory, or symlink to the source state\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots add [FILE...]\n"
+  printf "  archdots add --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "FILE..."
+    printf "\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_forget_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots forget - Remove a target from the source state\n"
+    echo
+
+  else
+    printf "archdots forget - Remove a target from the source state\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots forget [FILE...]\n"
+  printf "  archdots forget --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "FILE..."
+    printf "\n"
     echo
 
   fi
@@ -1213,6 +1319,193 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# archdots completion                                      -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_archdots_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_archdots_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'setup archdots_completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup git_credentials\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup audiorelay\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup git_delta\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup ssh_agent\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup amdgpupro\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup evrouter\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup monitors\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup docker\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup themes\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup rclone\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup nvim\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup cron\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup cups\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'list\'*\'dots\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help --pending --tree --unmanaged -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'list\'*\'apps\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help --pending --unmanaged -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup all\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--force --help --status -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup pip\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup amd\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sync apps\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help --remote -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sync dots\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sync all\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'cd dots\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'cd apps\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'forget\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'review\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'status\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'setup\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro archdots_completions audiorelay cron cups docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent themes")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'edit\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "$(pacdef group list) --help --list -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'diff\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sync\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all apps dots")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'list\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help --pending --unmanaged -h apps dots")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'add\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'git\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'cd\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h apps dots")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help --version -h -v add cd completions diff edit forget git list review setup status sync")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _archdots_completions archdots'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
 
 # :command.function
@@ -1623,6 +1916,43 @@ archdots_setup_cups_command() {
 }
 
 # :command.function
+archdots_completions_command() {
+  # src/commands/completions.sh
+  # echo "# this file is located in 'src/commands/completions.sh'"
+  # echo "# code for 'archdots completions' goes here"
+  # echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  # inspect_args
+
+  source ~/.local/share/chezmoi/archdots/src/lib/send_completions.sh
+  send_completions
+
+}
+
+# :command.function
+archdots_add_command() {
+  # src/commands/add.sh
+  # echo "# this file is located in 'src/commands/add.sh'"
+  # echo "# code for 'archdots add' goes here"
+  # echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  # inspect_args
+
+  bash -c "chezmoi add ${args[file]}"
+
+}
+
+# :command.function
+archdots_forget_command() {
+  # src/commands/forget.sh
+  # echo "# this file is located in 'src/commands/forget.sh'"
+  # echo "# code for 'archdots forget' goes here"
+  # echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  # inspect_args
+
+  bash -c "chezmoi forget ${args[file]}"
+
+}
+
+# :command.function
 archdots_edit_command() {
   # src/commands/edit.sh
 
@@ -1685,7 +2015,7 @@ archdots_sync_apps_command() {
   	echo "you have $unmanaged unmanaged packages"
 
   	if $(gum confirm "Review now?"); then
-  		pacdef package review
+  		$HOME/.local/share/chezmoi/archdots/archdots review
   	else
   		echo "Run 'archdots list --unmanaged' to view them or 'archdots review' to decide what to do with each one"
   	fi
@@ -1883,6 +2213,27 @@ parse_requirements() {
       action="setup"
       shift
       archdots_setup_parse_requirements "$@"
+      shift $#
+      ;;
+
+    completions)
+      action="completions"
+      shift
+      archdots_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
+    add)
+      action="add"
+      shift
+      archdots_add_parse_requirements "$@"
+      shift $#
+      ;;
+
+    forget)
+      action="forget"
+      shift
+      archdots_forget_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2921,6 +3272,150 @@ archdots_setup_cups_parse_requirements() {
 }
 
 # :command.parse_requirements
+archdots_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+archdots_add_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_add_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="add"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_repeatable
+
+        if [[ -z ${args['file']+x} ]]; then
+          args['file']="\"$1\""
+          shift
+        else
+          args['file']="${args[file]} \"$1\""
+          shift
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+archdots_forget_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_forget_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="forget"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_repeatable
+
+        if [[ -z ${args['file']+x} ]]; then
+          args['file']="\"$1\""
+          shift
+        else
+          args['file']="${args[file]} \"$1\""
+          shift
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 archdots_edit_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -3785,6 +4280,9 @@ run() {
     "setup amd") archdots_setup_amd_command ;;
     "setup amdgpupro") archdots_setup_amdgpupro_command ;;
     "setup cups") archdots_setup_cups_command ;;
+    "completions") archdots_completions_command ;;
+    "add") archdots_add_command ;;
+    "forget") archdots_forget_command ;;
     "edit") archdots_edit_command ;;
     "diff") archdots_diff_command ;;
     "sync") archdots_sync_command ;;
