oscYfsNk2TWMQrVV 05-02-2024

diff --git a/archdots/archdots b/archdots/archdots
--- a/archdots/archdots
+++ b/archdots/archdots
@@ -85,24 +85,25 @@ archdots_setup_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   \n" "$(green "all")            "
-  printf "  %s   \n" "$(green "git_credentials")"
-  printf "  %s   \n" "$(green "defaults")       "
-  printf "  %s   \n" "$(green "git_delta")      "
-  printf "  %s   \n" "$(green "nvim")           "
-  printf "  %s   \n" "$(green "evrouter")       "
-  printf "  %s   \n" "$(green "monitors")       "
-  printf "  %s   \n" "$(green "pip")            "
-  printf "  %s   \n" "$(green "docker")         "
-  printf "  %s   \n" "$(green "ssh_agent")      "
-  printf "  %s   \n" "$(green "rclone")         "
-  printf "  %s   \n" "$(green "cron")           "
-  printf "  %s   \n" "$(green "audiorelay")     "
-  printf "  %s   \n" "$(green "amd")            "
-  printf "  %s   \n" "$(green "amdgpupro")      "
-  printf "  %s   \n" "$(green "cups")           "
-  printf "  %s   \n" "$(green "desktop_entries")"
-  printf "  %s   \n" "$(green "display_manager")"
+  printf "  %s   \n" "$(green "all")             "
+  printf "  %s   \n" "$(green "git_credentials") "
+  printf "  %s   \n" "$(green "defaults")        "
+  printf "  %s   \n" "$(green "git_delta")       "
+  printf "  %s   \n" "$(green "nvim")            "
+  printf "  %s   \n" "$(green "evrouter")        "
+  printf "  %s   \n" "$(green "monitors")        "
+  printf "  %s   \n" "$(green "pip")             "
+  printf "  %s   \n" "$(green "docker")          "
+  printf "  %s   \n" "$(green "ssh_agent")       "
+  printf "  %s   \n" "$(green "rclone")          "
+  printf "  %s   \n" "$(green "cron")            "
+  printf "  %s   \n" "$(green "audiorelay")      "
+  printf "  %s   \n" "$(green "amd")             "
+  printf "  %s   \n" "$(green "amdgpupro")       "
+  printf "  %s   \n" "$(green "cups")            "
+  printf "  %s   \n" "$(green "desktop_entries") "
+  printf "  %s   \n" "$(green "display_manager") "
+  printf "  %s   \n" "$(green "terminal_history")"
   echo
 
   # :command.long_usage
@@ -642,6 +643,35 @@ archdots_setup_display_manager_usage() {
   printf "%s\n" "Usage:"
   printf "  archdots setup display_manager\n"
   printf "  archdots setup display_manager --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_setup_terminal_history_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots setup terminal_history\n"
+    echo
+
+  else
+    printf "archdots setup terminal_history\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots setup terminal_history\n"
+  printf "  archdots setup terminal_history --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1677,6 +1707,10 @@ send_completions() {
   echo $'  local compline="${compwords[*]}"'
   echo $''
   echo $'  case "$compline" in'
+  echo $'    \'setup terminal_history\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'setup git_credentials\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -1822,7 +1856,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'setup\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups defaults desktop_entries display_manager docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups defaults desktop_entries display_manager docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent terminal_history")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'edit\'*)'
@@ -2279,6 +2313,28 @@ archdots_setup_display_manager_command() {
 
   sudo cp $HOME/.local/share/chezmoi/archdots/public/lightdm.conf /etc/lightdm
   sudo cp $HOME/.local/share/chezmoi/archdots/public/lightdm-gtk-greeter.conf /etc/lightdm
+
+}
+
+# :command.function
+archdots_setup_terminal_history_command() {
+  # src/commands/setup/terminal_history.sh
+  #!/usr/bin/env bash
+
+  if [ "$1" = "check" ]; then
+  	if [[ -z "$(atuin status|rg 'Username: .{2,}')" ]]; then
+  		echo notok
+  	fi
+  	exit
+  fi
+
+  if gum confirm "Have you already registered to Atuin?"; then
+  	atuin login
+  else
+  	atuin register
+  fi
+  atuin import auto
+  atuin sync
 
 }
 
@@ -3152,6 +3208,13 @@ archdots_setup_parse_requirements() {
       shift $#
       ;;
 
+    terminal_history)
+      action="terminal_history"
+      shift
+      archdots_setup_terminal_history_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       archdots_setup_usage >&2
@@ -3971,6 +4034,50 @@ archdots_setup_display_manager_parse_requirements() {
 
   # :command.command_filter
   action="setup display_manager"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+archdots_setup_terminal_history_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_setup_terminal_history_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="setup terminal_history"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -5443,6 +5550,7 @@ run() {
     "setup cups") archdots_setup_cups_command ;;
     "setup desktop_entries") archdots_setup_desktop_entries_command ;;
     "setup display_manager") archdots_setup_display_manager_command ;;
+    "setup terminal_history") archdots_setup_terminal_history_command ;;
     "completions") archdots_completions_command ;;
     "add") archdots_add_command ;;
     "forget") archdots_forget_command ;;
