r5OaIjOmo3Bf8I1V 25-03-2024

diff --git a/archdots/archdots b/archdots/archdots
--- a/archdots/archdots
+++ b/archdots/archdots
@@ -87,6 +87,7 @@ archdots_setup_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   \n" "$(green "all")             "
   printf "  %s   \n" "$(green "git_credentials") "
+  printf "  %s   \n" "$(green "yay")             "
   printf "  %s   \n" "$(green "defaults")        "
   printf "  %s   \n" "$(green "git_delta")       "
   printf "  %s   \n" "$(green "nvim")            "
@@ -179,6 +180,35 @@ archdots_setup_git_credentials_usage() {
   printf "%s\n" "Usage:"
   printf "  archdots setup git_credentials\n"
   printf "  archdots setup git_credentials --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_setup_yay_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots setup yay\n"
+    echo
+
+  else
+    printf "archdots setup yay\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots setup yay\n"
+  printf "  archdots setup yay --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1803,6 +1833,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--force --help --status -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'setup yay\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'setup pip\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -1856,7 +1890,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'setup\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups defaults desktop_entries display_manager docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent terminal_history")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_archdots_completions_filter "--help -h all amd amdgpupro audiorelay cron cups defaults desktop_entries display_manager docker evrouter git_credentials git_delta monitors nvim pip rclone ssh_agent terminal_history yay")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'edit\'*)'
@@ -1955,6 +1989,22 @@ archdots_setup_git_credentials_command() {
 
   [ -n "$useremail" ]&&git config --global user.email "$useremail"||echo "Empty input. Did not change previous"
   [ -n "$username" ]&&git config --global user.name "$username"||echo "Empty input. Did not change previous"
+
+}
+
+# :command.function
+archdots_setup_yay_command() {
+  # src/commands/setup/yay.sh
+  #!/usr/bin/env bash
+
+  if [ "$1" = "check" ]; then
+  	if [ ! -f "$(which yay)" ]; then
+  		echo notok
+  	fi
+  	exit
+  fi
+
+  (git clone https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si)
 
 }
 
@@ -3096,6 +3146,13 @@ archdots_setup_parse_requirements() {
       shift $#
       ;;
 
+    yay)
+      action="yay"
+      shift
+      archdots_setup_yay_parse_requirements "$@"
+      shift $#
+      ;;
+
     defaults)
       action="defaults"
       shift
@@ -3330,6 +3387,50 @@ archdots_setup_git_credentials_parse_requirements() {
 
   # :command.command_filter
   action="setup git_credentials"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+archdots_setup_yay_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_setup_yay_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="setup yay"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -5534,6 +5635,7 @@ run() {
     "setup") archdots_setup_command ;;
     "setup all") archdots_setup_all_command ;;
     "setup git_credentials") archdots_setup_git_credentials_command ;;
+    "setup yay") archdots_setup_yay_command ;;
     "setup defaults") archdots_setup_defaults_command ;;
     "setup git_delta") archdots_setup_git_delta_command ;;
     "setup nvim") archdots_setup_nvim_command ;;
