M6jpkzvCEYcE5bY4 29-09-2023

diff --git a/archdots/archdots b/archdots/archdots
--- a/archdots/archdots
+++ b/archdots/archdots
@@ -34,13 +34,14 @@ archdots_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Run a setup script\n" "setup"
-  printf "  %s   edit packages file\n" "edit "
-  printf "  %s   show diff since last dotfiles sync\n" "diff "
-  printf "  %s   Sync apps and dotfiles\n" "sync "
-  printf "  %s   go to chezmoi repo or pacdef groups folder location\n" "cd   "
-  printf "  %s   run git commands from chezmoi repo\n" "git  "
-  printf "  %s   list all packages separated by group\n" "list "
+  printf "  %s   Run a setup script\n" "setup "
+  printf "  %s   edit packages file\n" "edit  "
+  printf "  %s   show diff since last dotfiles sync\n" "diff  "
+  printf "  %s   Sync apps and dotfiles\n" "sync  "
+  printf "  %s   go to chezmoi repo or pacdef groups folder location\n" "cd    "
+  printf "  %s   an alias for archdots git status\n" "status"
+  printf "  %s   run git commands from chezmoi repo\n" "git   "
+  printf "  %s   list all packages separated by group\n" "list  "
   echo
 
   # :command.long_usage
@@ -335,13 +336,19 @@ archdots_sync_apps_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  archdots sync apps\n"
+  printf "  archdots sync apps [OPTIONS]\n"
   printf "  archdots sync apps --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--remote"
+    printf "    only use remote changes\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -458,6 +465,35 @@ archdots_cd_apps_usage() {
   printf "%s\n" "Usage:"
   printf "  archdots cd apps\n"
   printf "  archdots cd apps --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+archdots_status_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "archdots status - an alias for archdots git status\n"
+    echo
+
+  else
+    printf "archdots status - an alias for archdots git status\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  archdots status\n"
+  printf "  archdots status --help | -h\n"
   echo
 
   # :command.long_usage
@@ -718,7 +754,11 @@ archdots_sync_dots_command() {
   # src/sync_dots_command.sh
 
   cd ~/.local/share/chezmoi
+
   git add .
+  if [[ ${args[--remote]} -ne 1 ]]; then
+  	chezmoi re-add
+  fi
   chezmoi update||echo Failed to update
 
   git diff --cached --stat
@@ -774,6 +814,18 @@ archdots_cd_apps_command() {
 }
 
 # :command.function
+archdots_status_command() {
+  # src/status_command.sh
+  # echo "# this file is located in 'src/status_command.sh'"
+  # echo "# code for 'archdots status' goes here"
+  # echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  # inspect_args
+
+  "$(dirname $0)/archdots" git status
+
+}
+
+# :command.function
 archdots_git_command() {
   # src/git_command.sh
   # echo "# this file is located in 'src/git_command.sh'"
@@ -781,7 +833,8 @@ archdots_git_command() {
   # echo "# you can edit it freely and regenerate (it will not be overwritten)"
   # inspect_args
 
-  chezmoi git ${other_args[@]}
+  cd ~/.local/share/chezmoi
+  git ${other_args[@]}
 
 }
 
@@ -858,6 +911,13 @@ parse_requirements() {
       action="cd"
       shift
       archdots_cd_parse_requirements "$@"
+      shift $#
+      ;;
+
+    status)
+      action="status"
+      shift
+      archdots_status_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1378,6 +1438,13 @@ archdots_sync_apps_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --remote)
+
+        # :flag.case_no_arg
+        args['--remote']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -1604,6 +1671,50 @@ archdots_cd_apps_parse_requirements() {
 }
 
 # :command.parse_requirements
+archdots_status_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        archdots_status_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="status"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 archdots_git_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -1735,6 +1846,7 @@ run() {
     "cd") archdots_cd_command ;;
     "cd dots") archdots_cd_dots_command ;;
     "cd apps") archdots_cd_apps_command ;;
+    "status") archdots_status_command ;;
     "git") archdots_git_command ;;
     "list") archdots_list_command ;;
   esac
